sudo: required
services:
  - docker

before_install:
  - docker build -t romulo2franca/docker-react -f Dockerfile.dev .

script:
  - docker run romulo2franca/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-281515538846"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY